# This is a basic workflow to help you get started with Actions

name: CI Pipeline

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # for running manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Get Secrets
        run: |
          echo ${{ secrets.MY_SUPER_SECRET}}
          echo ${{ secrets.MY_NON_EXISTENT_SECRET}}

      - name: Install prod dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
            pytest tests/

      - name: Run Static Code Analysis
        run: |
          pylint **/*.py
        continue-on-error: true

      - name: Run Type Checks
        run: |
          mypy .
        continue-on-error: true

      - name: Run Safety Check (vulnerabilities in libraries)
        run: |
          safety check
        continue-on-error: true

      - name: Run Security Check
        run: |
           bandit -r .
        continue-on-error: true

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t my-image-name:latest .
          
      - name: List Docker images
        run: |
          echo "Listing Docker images..."
          docker images

      - name: Run a one-line script
        run: echo Pipeline successfully finished!
