# This is a basic workflow to help you get started with Actions

name: CD Pipeline - pushing Docker to ACR

# Controls when the workflow will run
on:
  push:
    branches: [ "main-123" ]
  pull_request:
    branches: [ "main-123" ]

  # for running manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: 'Docker Login'
        uses: azure/docker-login@v1
#        uses: docker/login-action@v3 - to be used with Service Principal
        with:
          login-server: ${{secrets.ACR_ENDPOINT}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build the image and push it to ACR
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{secrets.ACR_ENDPOINT}}/my-image:latest
