# This is a basic workflow to help you get started with Actions

name: CD Pipeline - Deploying Docker image to Web App

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["CD Pipeline - pushing Docker to ACR"]
    types:
      - completed

  # for running manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az webapp list --output table

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ros-test-123'
          images: 'rosapostol.azurecr.io/my-image:latest'
      #
      #      - name: Azure CLI script
      #        uses: azure/cli@v2
      #        with:
      #          azcliversion: latest
      #          inlineScript: |
      #            az account show